apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 12Gi
  hostPath:
    path: /ghost/storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 6Gi